name: MessagesOnHead
version: '${project.version}'
main: mrquackduck.messagesonhead.MessagesOnHeadPlugin
api-version: '1.21.4'

commands:
  messagesonhead:
    description: The MessagesOnHead command
    aliases:
      - moh

permissions:
  messagesonhead.show:
    description: Whether messages will appear above player's head
    default: true
  messagesonhead.toggle:
    description: Whether players can toggle on/off seeing messages above other players' heads
    default: true
  messagesonhead.admin:
    description: Allows to use staff commands of the plugin
    default: op

softdepend: [PlaceholderAPI, ZelChat]
